version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn --bind 0.0.0.0:8080 --workers 3 backend.wsgi:application
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: timescale/timescaledb:latest-pg15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # Optional TimescaleDB tuning for production:
    # command: ["-c", "shared_preload_libraries=timescaledb"]
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

volumes:
  postgres_data: